# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: github-pages-index
          path: |
            ./src/main/resources/index.html
          retention-days: 1

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #    - name: Update dependency graph
  #      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  style:
    runs-on: ubuntu-latest
    name: Code Style
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle
        run: mvn -B verify checkstyle:checkstyle

      - name: Attach Checkstyle to Commit
        #        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        uses: cmelchior/checkstyle-github-action@4d748d6e705b05beb7cf4443c9d09d3226828114
        with:
          path: '**/checkstyle-result.xml'

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: checkstyle-output
          path: |
            ./target/site/checkstyle.html
            ./target/site/css
            ./target/site/images
          retention-days: 1

  coverage:
    runs-on: ubuntu-latest
    name: Mutation Testing
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run Mutation Testing
        run: mvn package org.pitest:pitest-maven:mutationCoverage jacoco:report

      # Still evaluating this!! Currently doesn't seem to be working
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./target/site/jacoco/jacoco.csv

      # Still evaluating this!!
      - name: Publish Pitest Report
        uses: Bonajo/pitest-report-action@v0.4
        with:
          file: ./target/site/pit/mutations.xml
      ###

      - name: Store coverage artefacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-output
          path: |
            ./target/site/pit
            ./target/site/jacoco
          retention-days: 1

  deploy-github-pages:
    runs-on: ubuntu-latest
    name: Deploy Reports to GitHub Pages
    needs: [style, coverage]
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: checkstyle-output
          path: ./target/site

      - uses: actions/download-artifact@v3.0.2
        with:
          name: coverage-output
          path: ./target/site

      - uses: actions/download-artifact@v3.0.2
        with:
          name: github-pages-index
          path: ./target/site

      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/
          commit_message: ${{ github.event.head_commit.message }}
